modLoader="javafml"
loaderVersion="[39,)"
license="The Apache License, Version 2.0"
issueTrackerURL="http://www.github.com/MelanX/recipeprinter/issues/"

[[mods]]
modId="recipeprinter"
version="${file.jarVersion}"
displayName="Recipe Printer"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/recipeprinter.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="recipedrawer.png"
credits=""
authors="MelanX, noeppi_noeppi"
description='''

'''

[[dependencies.recipeprinter]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.recipeprinter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1, 1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.recipeprinter]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.1-3.1,)"
    ordering="NONE"
    side="BOTH"