modLoader="javafml"
loaderVersion="[41,)"
license="The Apache License, Version 2.0"
issueTrackerURL="http://www.github.com/MelanX/recipeprinter/issues/"

[[mods]]
modId="recipeprinter"
version="${file.jarVersion}"
displayName="Recipe Printer"
updateJSONURL="https://assets.melanx.de/updates/recipe-printer.json"
displayURL="www.curseforge.com/members/melanx/"
credits=""
authors="MelanX, noeppi_noeppi"
description='''
Print recipes to showcase them
'''

[[dependencies.recipeprinter]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.recipeprinter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.recipeprinter]]
    modId="libx"
    mandatory=true
    versionRange="[1.19-4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.recipeprinter]]
    modId="jei"
    mandatory=false
    versionRange="[11,)"
    ordering="NONE"
    side="BOTH"
